import path from 'node:path';

import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { Pool } from 'pg';

import { env } from '../config/env';
import * as schema from './schema';

let pool: Pool | undefined;

function getPool(connectionString = env.databaseUrl) {
  if (!pool) {
    pool = new Pool({ connectionString });
  }

  return pool;
}

async function waitForDatabase(connectionString = env.databaseUrl, retries = 15) {
  const probe = new Pool({ connectionString });

  try {
    for (let attempt = 1; attempt <= retries; attempt++) {
      try {
        await probe.query('SELECT 1');
        return;
      } catch {
        if (attempt === retries) {
          throw new Error(`Database not reachable (check DATABASE_URL)`);
        }

        await new Promise((resolve) => setTimeout(resolve, 1000));
      }
    }
  } finally {
    await probe.end();
  }
}

function redactDatabaseUrl(connectionString: string) {
  try {
    const url = new URL(connectionString);
    if (url.password) {
      url.password = '***';
    }

    return url.toString();
  } catch {
    return '[invalid DATABASE_URL]';
  }
}

/** Open a typed Drizzle client. Tables are defined in `./schema.ts`. */
export function createDatabase(connectionString = env.databaseUrl) {
  return drizzle(getPool(connectionString), { schema });
}

/** Apply SQL migrations from `./drizzle/` (generated by `bun run db:generate`). */
export async function migrateDatabase(connectionString = env.databaseUrl) {
  await waitForDatabase(connectionString);

  const migrationPool = new Pool({ connectionString });
  const db = drizzle(migrationPool);

  try {
    await migrate(db, { migrationsFolder: path.resolve('drizzle') });
  } finally {
    await migrationPool.end();
  }

  return redactDatabaseUrl(connectionString);
}

export async function closeDatabase() {
  await pool?.end();
  pool = undefined;
}

export type AppDatabase = ReturnType<typeof createDatabase>;
