export const CLINICA_PASSPORT_STRATEGY = 'clinica';

export const CLINICA_SESSION_REFRESH_MS = 900_000;
export const CLINICA_SESSION_MAX_AGE_MS = 1_200_000;
export const CLINICA_SESSION_REFRESH_SAFETY_MS = 60_000;
export const CLINICA_HTTP_TIMEOUT_MS = 30_000;
export const CLINICA_RETRY_MAX_ATTEMPTS = 3;
export const CLINICA_RETRY_BASE_DELAY_MS = 1_000;
